version: '3.7'

networks:
  psalm_plugin_rdkafka_network:
    name: psalm_plugin_rdkafka_network
    driver: bridge

volumes:
  app_database: {}

services:
  php_psalm_plugin_rdkafka:
    build: php
    volumes:
      - ../:/var/www/app
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - psalm_plugin_rdkafka_network
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history